package:
  name: cnvkit
  version: "dev"

source:
  path: ../../

build:
  number: 0
  skip: False

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - atlas # [not osx]
    - biopython >=1.62
    - future >=0.15.2
    - futures >=3.0
    - matplotlib >=1.3.1
    - numpy >=1.9
    - pandas >=0.18.1
    - pyfaidx >=0.4.7
    - pysam >=0.10.0
    - reportlab >=3.0
    - scipy >=0.15.0
    - bioconductor-dnacopy
    - r-cghflasso

test:
  imports:
    - cnvlib
    - skgenome
  commands:
    - cnvkit.py -h

about:
  home: https://github.com/etal/cnvkit
  license: Apache License 2.0
  summary: Copy number variant detection from high-throughput sequencing
